/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 23162243
 */
public class ListaFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form ListaFuncionario
     */
    public ListaFuncionario() {
        this.setResizable(false);
        initComponents();
        BPreencher.setBackground(new java.awt.Color(0,0,0,1));
        Voltar2Menu1.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BPreencher = new javax.swing.JButton();
        Voltar2Menu1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 660));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        BPreencher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BPreencher.setForeground(new java.awt.Color(255, 255, 255));
        BPreencher.setText("Preencher");
        BPreencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPreencherActionPerformed(evt);
            }
        });
        jPanel1.add(BPreencher);
        BPreencher.setBounds(900, 570, 100, 40);

        Voltar2Menu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Voltar2Menu1.setForeground(new java.awt.Color(255, 255, 255));
        Voltar2Menu1.setText("Voltar");
        Voltar2Menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Voltar2Menu1ActionPerformed(evt);
            }
        });
        jPanel1.add(Voltar2Menu1);
        Voltar2Menu1.setBounds(790, 570, 100, 40);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        tabela.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane1.setViewportView(tabela);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 160, 910, 400);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\23162243\\Downloads\\WhatsApp Image 2023-05-25 at 21.22.47.jpeg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1050, 660);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1050, 660);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BPreencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPreencherActionPerformed
       try {
            DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
            if (modelo.getRowCount() > 0) {
                modelo.setRowCount(0);
            }

            String dir = System.getProperty("user.home")+"\\Desktop";
            String nomeArq = "funcionarios.csv";
            File arquivo = new File(dir, nomeArq);

            FileInputStream fis = new FileInputStream(arquivo);
            InputStreamReader isr = new InputStreamReader(fis);
            BufferedReader br = new BufferedReader(isr);

            String linha = br.readLine();
            while (linha != null) {
                Object[] obj = linha.split(";");
                modelo.addRow(obj);
                linha = br.readLine();
            }
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Arquivo não encontrado!!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "ERRO");
        }
    }//GEN-LAST:event_BPreencherActionPerformed

    private void Voltar2Menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Voltar2Menu1ActionPerformed
       new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_Voltar2Menu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BPreencher;
    private javax.swing.JButton Voltar2Menu1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
