package Login;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Antonio
 */
public class loading1 extends javax.swing.JFrame {

    /**
     * Creates new form Loading
     */
    public loading1() {
        this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Porcentagem = new javax.swing.JLabel();
        Progresso = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(756, 546));
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanel1.setLayout(null);

        Porcentagem.setBackground(new java.awt.Color(255, 255, 255));
        Porcentagem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Porcentagem.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Porcentagem);
        Porcentagem.setBounds(690, 440, 50, 40);

        Progresso.setForeground(new java.awt.Color(153, 102, 255));
        jPanel1.add(Progresso);
        Progresso.setBounds(0, 490, 750, 10);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\23162243\\Desktop\\ImagenLoginBy.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-3, -4, 760, 530);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 520);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        {
            loading1 loading = new loading1();
            loading.setVisible(true);
            try {
                for (int i = 0; i <= 100; i += 3) {
                    Thread.sleep(70);
                    loading.Progresso.setValue(i);
                    loading.Porcentagem.setText(Integer.toString(i) + "%");
                }

                loading.dispose();

            } catch (InterruptedException e) {
                JOptionPane.showConfirmDialog(null, "ERRO");
            }
        }

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loading1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loading1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loading1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loading1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
                new loading1().setVisible(false);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Porcentagem;
    private javax.swing.JProgressBar Progresso;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
