/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import javax.swing.JOptionPane;

/**
 *
 * @author Antonio
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        this.setResizable(false);
        initComponents();
        BClientes.setBackground(new java.awt.Color(0,0,0,0));
        BLista.setBackground(new java.awt.Color(0,0,0,0));
        Bregistrarcli.setBackground(new java.awt.Color(0,0,0,0));
        BDeslogar.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BClientes = new javax.swing.JButton();
        BLista = new javax.swing.JButton();
        Bregistrarcli = new javax.swing.JButton();
        BDeslogar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 570));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        BClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BClientesActionPerformed(evt);
            }
        });
        jPanel1.add(BClientes);
        BClientes.setBounds(250, 240, 410, 50);

        BLista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BListaActionPerformed(evt);
            }
        });
        jPanel1.add(BLista);
        BLista.setBounds(250, 330, 410, 50);

        Bregistrarcli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bregistrarcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BregistrarcliActionPerformed(evt);
            }
        });
        jPanel1.add(Bregistrarcli);
        Bregistrarcli.setBounds(250, 430, 410, 50);

        BDeslogar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BDeslogar.setForeground(new java.awt.Color(255, 255, 255));
        BDeslogar.setText("Deslogar");
        BDeslogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDeslogarActionPerformed(evt);
            }
        });
        jPanel1.add(BDeslogar);
        BDeslogar.setBounds(720, 450, 110, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\23162243\\Downloads\\imagem.menu.atualizada.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-3, -4, 890, 540);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 890, 530);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BClientesActionPerformed
      new TelaAgenda().setVisible(true);
           dispose();
    }//GEN-LAST:event_BClientesActionPerformed

    private void BregistrarcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BregistrarcliActionPerformed
        new RegistrarClientes().setVisible(true);
           dispose();
    }//GEN-LAST:event_BregistrarcliActionPerformed

    private void BListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BListaActionPerformed
         new ListaFuncionario().setVisible(true);
           dispose();
    }//GEN-LAST:event_BListaActionPerformed

    private void BDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDeslogarActionPerformed
          int resposta = JOptionPane.showConfirmDialog(null, "Deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        
        if (resposta == JOptionPane.YES_OPTION) {
            new TelaLogin().setVisible(true);
            dispose();
            // Aqui você pode adicionar o código para encerrar o programa
        } 
    }//GEN-LAST:event_BDeslogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BClientes;
    private javax.swing.JButton BDeslogar;
    private javax.swing.JButton BLista;
    private javax.swing.JButton Bregistrarcli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
