package Login;

import java.util.ArrayList;
import ByBlockClass.AppCliente;
import ByBlockClass.ClassCliente;
import ByBlockClass.GerarCSV;
import java.util.Vector;
import ByBlockClass.ClassCliente;

/**
 *
 * @author 23162243
 */
public class RegistrarClientes extends javax.swing.JFrame {
    ClassCliente cc = new ClassCliente();
    
    AppCliente marca;
    AppCliente cnpj;
    AppCliente produto;
    AppCliente celular;
    AppCliente email;
    AppCliente clientep;
    Vector<String> cp;

    public RegistrarClientes() {
        this.setResizable(false);
        clientep = new AppCliente();
        cp = new Vector<String>();

        initComponents();
        BSair.setBackground(new java.awt.Color(0, 0, 0, 1));
        BSalvar.setBackground(new java.awt.Color(0, 0, 0, 1));
        CampNomeDaMarca.setBackground(new java.awt.Color(0, 0, 0, 1));
        CampSegmentoDeProdutos.setBackground(new java.awt.Color(0, 0, 0, 1));
        CampCNPJ.setBackground(new java.awt.Color(0, 0, 0, 1));
        CampEmail.setBackground(new java.awt.Color(0, 0, 0, 1));
        CampCelular.setBackground(new java.awt.Color(0, 0, 0, 1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BSalvar = new javax.swing.JButton();
        BSair = new javax.swing.JButton();
        CampNomeDaMarca = new javax.swing.JTextField();
        CampSegmentoDeProdutos = new javax.swing.JTextField();
        CampCNPJ = new javax.swing.JTextField();
        CampEmail = new javax.swing.JTextField();
        CampCelular = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Listacliente = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(823, 464));

        jPanel1.setLayout(null);

        BSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BSalvar.setForeground(new java.awt.Color(255, 255, 255));
        BSalvar.setText("Salvar");
        BSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(BSalvar);
        BSalvar.setBounds(640, 410, 120, 40);

        BSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BSair.setForeground(new java.awt.Color(255, 255, 255));
        BSair.setText("Voltar");
        BSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSairActionPerformed(evt);
            }
        });
        jPanel1.add(BSair);
        BSair.setBounds(510, 410, 120, 40);

        CampNomeDaMarca.setBackground(new java.awt.Color(0, 0, 0));
        CampNomeDaMarca.setForeground(new java.awt.Color(255, 255, 255));
        CampNomeDaMarca.setBorder(null);
        CampNomeDaMarca.setCaretColor(new java.awt.Color(255, 255, 255));
        CampNomeDaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampNomeDaMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(CampNomeDaMarca);
        CampNomeDaMarca.setBounds(50, 150, 410, 20);

        CampSegmentoDeProdutos.setForeground(new java.awt.Color(255, 255, 255));
        CampSegmentoDeProdutos.setBorder(null);
        jPanel1.add(CampSegmentoDeProdutos);
        CampSegmentoDeProdutos.setBounds(50, 276, 410, 20);

        CampCNPJ.setForeground(new java.awt.Color(255, 255, 255));
        CampCNPJ.setBorder(null);
        jPanel1.add(CampCNPJ);
        CampCNPJ.setBounds(50, 210, 160, 20);

        CampEmail.setForeground(new java.awt.Color(255, 255, 255));
        CampEmail.setBorder(null);
        jPanel1.add(CampEmail);
        CampEmail.setBounds(120, 350, 340, 16);

        CampCelular.setForeground(new java.awt.Color(255, 255, 255));
        CampCelular.setBorder(null);
        jPanel1.add(CampCelular);
        CampCelular.setBounds(570, 350, 170, 20);

        jScrollPane1.setViewportView(Listacliente);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(520, 130, 280, 190);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\23162243\\Downloads\\cada-byblock.PNG")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-3, -4, 820, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSairActionPerformed
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_BSairActionPerformed

    private void CampNomeDaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampNomeDaMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampNomeDaMarcaActionPerformed

    private void BSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalvarActionPerformed

        ClassCliente c = new ClassCliente();
        c.setMarca(CampNomeDaMarca.getText());
        c.setCelular(CampCelular.getText());
        c.setCnpj(CampCNPJ.getText());
        c.setEmail(CampEmail.getText());
        c.setProduto(CampSegmentoDeProdutos.getText());

        clientep.insereCliente(c);
        //cp.add(c.getMarca()+ c.getCnpj(),
        cp.add("Marca: " + c.getMarca());
        cp.add("CNPJ : " + c.getCnpj());
        cp.add("Produto: " + c.getProduto());
        cp.add("Email: " + c.getEmail());
        cp.add("Celular: " + c.getCelular());
        Listacliente.setListData(cp);
         ArrayList<String> lista = new ArrayList<String>();
         lista.add("Marca: " + c.getMarca());
         lista.add("CNPJ : " + c.getCnpj());
         lista.add("Produto: " + c.getProduto());
        GerarCSV file = new GerarCSV();
        String DIR = "C:\\Users\\23162243\\Documents\\";
        String FILE = "cliente.csv";
        file.escrita(lista ,DIR,FILE);	


    }//GEN-LAST:event_BSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BSair;
    private javax.swing.JButton BSalvar;
    private javax.swing.JTextField CampCNPJ;
    private javax.swing.JTextField CampCelular;
    private javax.swing.JTextField CampEmail;
    private javax.swing.JTextField CampNomeDaMarca;
    private javax.swing.JTextField CampSegmentoDeProdutos;
    private javax.swing.JList<String> Listacliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
