/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 23162243
 */
public class TelaAgenda extends javax.swing.JFrame {
       
    /**
     * Creates new form TelaAgenda
     */
    public TelaAgenda() {
        this.setResizable(false);
        initComponents();
        BSalvar.setBackground(new java.awt.Color(0,0,0,1));
        BApagar.setBackground(new java.awt.Color(0,0,0,1));
        BVoltar1.setBackground(new java.awt.Color(0,0,0,1));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        BApagar = new javax.swing.JButton();
        BSalvar = new javax.swing.JButton();
        BVoltar1 = new javax.swing.JButton();
        CampData = new javax.swing.JTextField();
        CampHora = new javax.swing.JTextField();
        CampEvento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agenda");
        setMinimumSize(new java.awt.Dimension(1078, 610));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Evento", "Data", "Hora"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(170, 240, 700, 270);

        BApagar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BApagar.setForeground(new java.awt.Color(255, 255, 255));
        BApagar.setText("Apagar");
        BApagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BApagarActionPerformed(evt);
            }
        });
        jPanel1.add(BApagar);
        BApagar.setBounds(820, 520, 100, 40);

        BSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BSalvar.setForeground(new java.awt.Color(255, 255, 255));
        BSalvar.setText("Salvar");
        BSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(BSalvar);
        BSalvar.setBounds(930, 520, 100, 40);

        BVoltar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BVoltar1.setForeground(new java.awt.Color(255, 255, 255));
        BVoltar1.setText("Voltar");
        BVoltar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVoltar1ActionPerformed(evt);
            }
        });
        jPanel1.add(BVoltar1);
        BVoltar1.setBounds(710, 520, 100, 40);
        jPanel1.add(CampData);
        CampData.setBounds(370, 150, 330, 30);
        jPanel1.add(CampHora);
        CampHora.setBounds(720, 150, 320, 30);

        CampEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampEventoActionPerformed(evt);
            }
        });
        jPanel1.add(CampEvento);
        CampEvento.setBounds(30, 150, 320, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\23162243\\Desktop\\imagemAgenda.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(3, 0, 1060, 580);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1060, 580);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalvarActionPerformed
       
        String nome = CampEvento.getText().trim();
        String data = CampData.getText().trim();
        String hora = CampHora.getText().trim();
        
        DefaultTableModel val = (DefaultTableModel) tabela.getModel();
        val.addRow(new String []{nome, data, hora});
        CampData.setText("");
        CampEvento.setText("");
        CampHora.setText("");
        CampEvento.requestFocus();
        
        
    }//GEN-LAST:event_BSalvarActionPerformed

    private void BApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BApagarActionPerformed
       
        ((DefaultTableModel) tabela.getModel()).removeRow(tabela.getSelectedRow());
        
        
    }//GEN-LAST:event_BApagarActionPerformed

    private void BVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVoltar1ActionPerformed
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_BVoltar1ActionPerformed

    private void CampEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampEventoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BApagar;
    private javax.swing.JButton BSalvar;
    private javax.swing.JButton BVoltar1;
    private javax.swing.JTextField CampData;
    private javax.swing.JTextField CampEvento;
    private javax.swing.JTextField CampHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
